/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivacyLottery } from "./PrivacyLottery";
export type { PrivacyLotteryFHE } from "./PrivacyLotteryFHE";
