/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivacyLotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createLottery"
      | "drawWinner"
      | "enterLottery"
      | "getLotteryState"
      | "getParticipants"
      | "getParticipantsCount"
      | "getPrizeDescription"
      | "lotteries"
      | "lotteryCounter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LotteryCreated"
      | "ParticipantEntered"
      | "WinnerDrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createLottery",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "drawWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enterLottery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLotteryState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantsCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrizeDescription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryCounter",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drawWinner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enterLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLotteryState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrizeDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lotteries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lotteryCounter",
    data: BytesLike
  ): Result;
}

export namespace LotteryCreatedEvent {
  export type InputTuple = [
    lotteryId: BigNumberish,
    creator: AddressLike,
    prizeDescription: string,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    lotteryId: bigint,
    creator: string,
    prizeDescription: string,
    deadline: bigint
  ];
  export interface OutputObject {
    lotteryId: bigint;
    creator: string;
    prizeDescription: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantEnteredEvent {
  export type InputTuple = [lotteryId: BigNumberish, participant: AddressLike];
  export type OutputTuple = [lotteryId: bigint, participant: string];
  export interface OutputObject {
    lotteryId: bigint;
    participant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerDrawnEvent {
  export type InputTuple = [lotteryId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [lotteryId: bigint, winner: string];
  export interface OutputObject {
    lotteryId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivacyLottery extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyLottery;
  waitForDeployment(): Promise<this>;

  interface: PrivacyLotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createLottery: TypedContractMethod<
    [_prizeDescription: string, _deadline: BigNumberish],
    [void],
    "nonpayable"
  >;

  drawWinner: TypedContractMethod<
    [lotteryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  enterLottery: TypedContractMethod<
    [lotteryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getLotteryState: TypedContractMethod<
    [lotteryId: BigNumberish],
    [bigint],
    "view"
  >;

  getParticipants: TypedContractMethod<
    [lotteryId: BigNumberish],
    [string[]],
    "view"
  >;

  getParticipantsCount: TypedContractMethod<
    [lotteryId: BigNumberish],
    [bigint],
    "view"
  >;

  getPrizeDescription: TypedContractMethod<
    [lotteryId: BigNumberish],
    [string],
    "view"
  >;

  lotteries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        creator: string;
        prizeDescription: string;
        deadline: bigint;
        state: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  lotteryCounter: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createLottery"
  ): TypedContractMethod<
    [_prizeDescription: string, _deadline: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "drawWinner"
  ): TypedContractMethod<[lotteryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enterLottery"
  ): TypedContractMethod<[lotteryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLotteryState"
  ): TypedContractMethod<[lotteryId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<[lotteryId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getParticipantsCount"
  ): TypedContractMethod<[lotteryId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrizeDescription"
  ): TypedContractMethod<[lotteryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "lotteries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        creator: string;
        prizeDescription: string;
        deadline: bigint;
        state: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lotteryCounter"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LotteryCreated"
  ): TypedContractEvent<
    LotteryCreatedEvent.InputTuple,
    LotteryCreatedEvent.OutputTuple,
    LotteryCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantEntered"
  ): TypedContractEvent<
    ParticipantEnteredEvent.InputTuple,
    ParticipantEnteredEvent.OutputTuple,
    ParticipantEnteredEvent.OutputObject
  >;
  getEvent(
    key: "WinnerDrawn"
  ): TypedContractEvent<
    WinnerDrawnEvent.InputTuple,
    WinnerDrawnEvent.OutputTuple,
    WinnerDrawnEvent.OutputObject
  >;

  filters: {
    "LotteryCreated(uint256,address,string,uint256)": TypedContractEvent<
      LotteryCreatedEvent.InputTuple,
      LotteryCreatedEvent.OutputTuple,
      LotteryCreatedEvent.OutputObject
    >;
    LotteryCreated: TypedContractEvent<
      LotteryCreatedEvent.InputTuple,
      LotteryCreatedEvent.OutputTuple,
      LotteryCreatedEvent.OutputObject
    >;

    "ParticipantEntered(uint256,address)": TypedContractEvent<
      ParticipantEnteredEvent.InputTuple,
      ParticipantEnteredEvent.OutputTuple,
      ParticipantEnteredEvent.OutputObject
    >;
    ParticipantEntered: TypedContractEvent<
      ParticipantEnteredEvent.InputTuple,
      ParticipantEnteredEvent.OutputTuple,
      ParticipantEnteredEvent.OutputObject
    >;

    "WinnerDrawn(uint256,address)": TypedContractEvent<
      WinnerDrawnEvent.InputTuple,
      WinnerDrawnEvent.OutputTuple,
      WinnerDrawnEvent.OutputObject
    >;
    WinnerDrawn: TypedContractEvent<
      WinnerDrawnEvent.InputTuple,
      WinnerDrawnEvent.OutputTuple,
      WinnerDrawnEvent.OutputObject
    >;
  };
}
